<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="scheduler" nsURI="http://www.novosoft.net/tasker/scheduler"
    nsPrefix="scheduler">
  <eClassifiers xsi:type="ecore:EClass" name="Scheduler" eSuperTypes="Base.ecore#//Named">
    <eOperations name="pauseAll"/>
    <eOperations name="resumeAll"/>
    <eOperations name="pause">
      <eParameters name="jobs" upperBound="-1" eType="#//Job"/>
    </eOperations>
    <eOperations name="start" eExceptions="#//SchedulerException"/>
    <eOperations name="resume">
      <eParameters name="jobs" upperBound="-1" eType="#//Job"/>
    </eOperations>
    <eOperations name="shutdown">
      <eParameters name="waitForJobsToComplete" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jobs" upperBound="-1" eType="#//Job"
        eOpposite="#//Job/scheduler"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="started" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shutdown" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Job" eSuperTypes="Base.ecore#//Named Base.ecore#//Described">
    <eOperations name="execute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scheduler" eType="#//Scheduler"
        eOpposite="#//Scheduler/jobs"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="runTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trigger" eSuperTypes="Base.ecore#//Described">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="SchedulerException" instanceClassName="java.lang.Exception"/>
</ecore:EPackage>
